#####################################################################
#																	 
#	Created by u'nSP IDE		10:39:29	05/20/03
#
#####################################################################




APPDIR	= E:\PROGRA~1\Sunplus\STUDYU~1

OUTDIR	= .\Release

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"F:/SN03-TG028/语音电子钟"

BODY	= -body SPCE061A -bfile "$(APPDIR)\Body\SPCE061A.cpt"

BINFILE	= "$(OUTDIR)\Time.S37"

ARYFILE	= "$(OUTDIR)\Time.ary"

SBMFILE	= "$(OUTDIR)\Time.sbm"

OPT	= -S -O2

ASFLAGS	= -t2

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	=   

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\T040_16k.res" \
	"$(OUTDIR)\T041_16k.res" \
	"$(OUTDIR)\T042_16k.res" \
	"$(OUTDIR)\T043_16k.res" \
	"$(OUTDIR)\T044_16k.res" \
	"$(OUTDIR)\T045_16k.res" \
	"$(OUTDIR)\T046_16k.res" \
	"$(OUTDIR)\T047_16k.res" \
	"$(OUTDIR)\T048_16k.res" \
	"$(OUTDIR)\T049_16k.res" \
	"$(OUTDIR)\T050_16k.res" \
	"$(OUTDIR)\T051_16k.res" \
	"$(OUTDIR)\T052_16k.res" \
	"$(OUTDIR)\T053_16k.res" \
	"$(OUTDIR)\T054_16k.res" \
	"$(OUTDIR)\T055_16k.res" \
	"$(OUTDIR)\T056_16k.res" \
	"$(OUTDIR)\T057_16k.res" \
	"$(OUTDIR)\T058_16k.res" \
	"$(OUTDIR)\T059_16k.res" \
	"$(OUTDIR)\T060_16k.res" \
	"$(OUTDIR)\T061_16k.res" \
	"$(OUTDIR)\T062_16k.res" \
	"$(OUTDIR)\T063_16k.res" \
	"$(OUTDIR)\T064_16k.res" \
	"$(OUTDIR)\T065_16k.res" \
	"$(OUTDIR)\T066_16k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\main.obj" \
	"$(OUTDIR)\system.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\Key.obj" \
	"$(OUTDIR)\FIQ.obj" 

"$(OUTDIR)\T040_16k.res": "F:\SN03-TG028\语音电子钟\16k\T040.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T040.16k" "$(OUTDIR)\T040_16k.res" RES_T040_16K 

"$(OUTDIR)\T041_16k.res": "F:\SN03-TG028\语音电子钟\16k\T041.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T041.16k" "$(OUTDIR)\T041_16k.res" RES_T041_16K 

"$(OUTDIR)\T042_16k.res": "F:\SN03-TG028\语音电子钟\16k\T042.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T042.16k" "$(OUTDIR)\T042_16k.res" RES_T042_16K 

"$(OUTDIR)\T043_16k.res": "F:\SN03-TG028\语音电子钟\16k\T043.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T043.16k" "$(OUTDIR)\T043_16k.res" RES_T043_16K 

"$(OUTDIR)\T044_16k.res": "F:\SN03-TG028\语音电子钟\16k\T044.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T044.16k" "$(OUTDIR)\T044_16k.res" RES_T044_16K 

"$(OUTDIR)\T045_16k.res": "F:\SN03-TG028\语音电子钟\16k\T045.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T045.16k" "$(OUTDIR)\T045_16k.res" RES_T045_16K 

"$(OUTDIR)\T046_16k.res": "F:\SN03-TG028\语音电子钟\16k\T046.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T046.16k" "$(OUTDIR)\T046_16k.res" RES_T046_16K 

"$(OUTDIR)\T047_16k.res": "F:\SN03-TG028\语音电子钟\16k\T047.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T047.16k" "$(OUTDIR)\T047_16k.res" RES_T047_16K 

"$(OUTDIR)\T048_16k.res": "F:\SN03-TG028\语音电子钟\16k\T048.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T048.16k" "$(OUTDIR)\T048_16k.res" RES_T048_16K 

"$(OUTDIR)\T049_16k.res": "F:\SN03-TG028\语音电子钟\16k\T049.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T049.16k" "$(OUTDIR)\T049_16k.res" RES_T049_16K 

"$(OUTDIR)\T050_16k.res": "F:\SN03-TG028\语音电子钟\16k\T050.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T050.16k" "$(OUTDIR)\T050_16k.res" RES_T050_16K 

"$(OUTDIR)\T051_16k.res": "F:\SN03-TG028\语音电子钟\16k\T051.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T051.16k" "$(OUTDIR)\T051_16k.res" RES_T051_16K 

"$(OUTDIR)\T052_16k.res": "F:\SN03-TG028\语音电子钟\16k\T052.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T052.16k" "$(OUTDIR)\T052_16k.res" RES_T052_16K 

"$(OUTDIR)\T053_16k.res": "F:\SN03-TG028\语音电子钟\16k\T053.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T053.16k" "$(OUTDIR)\T053_16k.res" RES_T053_16K 

"$(OUTDIR)\T054_16k.res": "F:\SN03-TG028\语音电子钟\16k\T054.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T054.16k" "$(OUTDIR)\T054_16k.res" RES_T054_16K 

"$(OUTDIR)\T055_16k.res": "F:\SN03-TG028\语音电子钟\16k\T055.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T055.16k" "$(OUTDIR)\T055_16k.res" RES_T055_16K 

"$(OUTDIR)\T056_16k.res": "F:\SN03-TG028\语音电子钟\16k\T056.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T056.16k" "$(OUTDIR)\T056_16k.res" RES_T056_16K 

"$(OUTDIR)\T057_16k.res": "F:\SN03-TG028\语音电子钟\16k\T057.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T057.16k" "$(OUTDIR)\T057_16k.res" RES_T057_16K 

"$(OUTDIR)\T058_16k.res": "F:\SN03-TG028\语音电子钟\16k\T058.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T058.16k" "$(OUTDIR)\T058_16k.res" RES_T058_16K 

"$(OUTDIR)\T059_16k.res": "F:\SN03-TG028\语音电子钟\16k\T059.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T059.16k" "$(OUTDIR)\T059_16k.res" RES_T059_16K 

"$(OUTDIR)\T060_16k.res": "F:\SN03-TG028\语音电子钟\16k\T060.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T060.16k" "$(OUTDIR)\T060_16k.res" RES_T060_16K 

"$(OUTDIR)\T061_16k.res": "F:\SN03-TG028\语音电子钟\16k\T061.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T061.16k" "$(OUTDIR)\T061_16k.res" RES_T061_16K 

"$(OUTDIR)\T062_16k.res": "F:\SN03-TG028\语音电子钟\16k\T062.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T062.16k" "$(OUTDIR)\T062_16k.res" RES_T062_16K 

"$(OUTDIR)\T063_16k.res": "F:\SN03-TG028\语音电子钟\16k\T063.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T063.16k" "$(OUTDIR)\T063_16k.res" RES_T063_16K 

"$(OUTDIR)\T064_16k.res": "F:\SN03-TG028\语音电子钟\16k\T064.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T064.16k" "$(OUTDIR)\T064_16k.res" RES_T064_16K 

"$(OUTDIR)\T065_16k.res": "F:\SN03-TG028\语音电子钟\16k\T065.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T065.16k" "$(OUTDIR)\T065_16k.res" RES_T065_16K 

"$(OUTDIR)\T066_16k.res": "F:\SN03-TG028\语音电子钟\16k\T066.16k"
	$(RESC) "F:\SN03-TG028\语音电子钟\16k\T066.16k" "$(OUTDIR)\T066_16k.res" RES_T066_16K 

"$(OUTDIR)\Resource.obj": "F:\SN03-TG028\语音电子钟\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "F:\SN03-TG028\语音电子钟\Resource.asm" 

"$(OUTDIR)\main.obj": "F:\SN03-TG028\语音电子钟\main.c" ".\a2000.h" ".\consist.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "F:/SN03-TG028/语音电子钟/main.c" 
	$(AS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 

"$(OUTDIR)\system.obj": "F:\SN03-TG028\语音电子钟\system.asm" ".\hardware.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\system.lst" -o "$(OUTDIR)\system.obj" "F:\SN03-TG028\语音电子钟\system.asm" 

"$(OUTDIR)\hardware.obj": "F:\SN03-TG028\语音电子钟\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "F:\SN03-TG028\语音电子钟\hardware.asm" 

"$(OUTDIR)\Key.obj": "F:\SN03-TG028\语音电子钟\Key.asm" ".\hardware.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Key.lst" -o "$(OUTDIR)\Key.obj" "F:\SN03-TG028\语音电子钟\Key.asm" 

"$(OUTDIR)\FIQ.obj": "F:\SN03-TG028\语音电子钟\FIQ.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\FIQ.lst" -o "$(OUTDIR)\FIQ.obj" "F:\SN03-TG028\语音电子钟\FIQ.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\T040_16k.res" 
	$(RM) "$(OUTDIR)\T041_16k.res" 
	$(RM) "$(OUTDIR)\T042_16k.res" 
	$(RM) "$(OUTDIR)\T043_16k.res" 
	$(RM) "$(OUTDIR)\T044_16k.res" 
	$(RM) "$(OUTDIR)\T045_16k.res" 
	$(RM) "$(OUTDIR)\T046_16k.res" 
	$(RM) "$(OUTDIR)\T047_16k.res" 
	$(RM) "$(OUTDIR)\T048_16k.res" 
	$(RM) "$(OUTDIR)\T049_16k.res" 
	$(RM) "$(OUTDIR)\T050_16k.res" 
	$(RM) "$(OUTDIR)\T051_16k.res" 
	$(RM) "$(OUTDIR)\T052_16k.res" 
	$(RM) "$(OUTDIR)\T053_16k.res" 
	$(RM) "$(OUTDIR)\T054_16k.res" 
	$(RM) "$(OUTDIR)\T055_16k.res" 
	$(RM) "$(OUTDIR)\T056_16k.res" 
	$(RM) "$(OUTDIR)\T057_16k.res" 
	$(RM) "$(OUTDIR)\T058_16k.res" 
	$(RM) "$(OUTDIR)\T059_16k.res" 
	$(RM) "$(OUTDIR)\T060_16k.res" 
	$(RM) "$(OUTDIR)\T061_16k.res" 
	$(RM) "$(OUTDIR)\T062_16k.res" 
	$(RM) "$(OUTDIR)\T063_16k.res" 
	$(RM) "$(OUTDIR)\T064_16k.res" 
	$(RM) "$(OUTDIR)\T065_16k.res" 
	$(RM) "$(OUTDIR)\T066_16k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) "$(OUTDIR)\system.obj" 
	$(RM) "$(OUTDIR)\system.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\Key.obj" 
	$(RM) "$(OUTDIR)\Key.lst" 
	$(RM) "$(OUTDIR)\FIQ.obj" 
	$(RM) "$(OUTDIR)\FIQ.lst" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

